### ISSUE TITLE
sign out problem

### ISSUE THREAD

**Issue by jrprintin3d** [alexmamo/FirebaseAnonymousAuthentication#1]
I have an Issue with sign out. 
After sign out the current User, the Screen is toggled between AuthScreen and ProfileScreen for around 20s.

**Comment by AlexMamo** [comment]
Is your screen flickering? If that's the case most likely you have upgraded the navigation compose dependency to the latest version. There are two solutions to downgrade the dependency or use this [solution](https://stackoverflow.com/questions/68633717/topappbar-flashing-when-navigating-with-compose-navigation).

**Comment by jrprintin3d** [comment]
Thanks for your fast reply. 
I've found that if I implement "androidx.hilt:hilt-navigation-compose" instead of "androidx.navigation.navigation-compose", everything works.  But here, too, the same problem when I update from alpha03 to beta01.

**Comment by AlexMamo** [comment]
Try to update the Gradle to the latest version as in my updated repo and use the **exact** same versions I have used. It should work. If you want to use the latest versions, then you should consider using the solution in the first comment. Give it a try and tell me if it works.

**Comment by jrprintin3d** [comment]
When I use the exact same versions it works. Thank you very much
