### ISSUE TITLE
Article and repo not in sync

### ISSUE THREAD

**Issue by Subtextaps** [alexmamo/FirebaseAnonymousAuthentication#2]
Hi Alex,

There are several discrepancies between the repo and your article:
https://medium.com/firebase-tips-tricks/how-to-handle-firebase-authentication-in-clean-architecture-using-jetpack-compose-e9929c0e31f8

E.g. the parts about the AuthStateListener are missing from the repo.

Could you please update the repo with the missing parts. Would be highly appreciated.

Thanks for sharing,

Thomas

**Comment by AlexMamo** [comment]
Hey,
Thanks for reaching out. Actually, the repo has some improvements. That AuthStateListener is actually not needed, since we explicitly navigate from one screen to another. I hope I'll find some time to update the article.
